# Site settings
title: ::bholley
email: bobbyholley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bobby Holley - Mozilla Hacker & Everything Else.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bholley.net" # the base hostname & protocol for your site

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "blog/:categories/:year/:title.html"

# Build settings
markdown: kramdown
